const DEFAULTS = {
  enabled: true,
  apiBase: "http://127.0.0.1:8765",
  apiToken: "",
  language: "zh-TW",
  showSource: false,
  bilingual: false,
  order: "translation-first",
  displayMode: "normal",
  horizontalPosition: "center",
  fontSize: 28,
  verticalPosition: 12,
  stackMaxItems: 4,
  stackDirection: "up",
  stackPastOpacity: 0.55,
  stackPastScale: 0.82,
  background: true,
  shadow: true,
  backgroundOpacity: 0.62,
  autoLoad: true,
  autoCreateJob: false,
  toolbar: true,
  shortcutToggle: "Alt+S",
  shortcutMode: "Alt+B",
  shortcutFontUp: "Alt+=",
  shortcutFontDown: "Alt+-",
  shortcutUp: "Alt+ArrowUp",
  shortcutDown: "Alt+ArrowDown",
};

const LANGUAGE_OPTIONS = [
  ["zh-TW", "繁體中文"],
  ["en", "English"],
  ["ja", "日本語"],
];
